Don't hide error for missing runtime on start
When using the m2ee cli in one-off mode, it would report success when
doing start when the runtime is missing. Make the error bubble up to the
top level error handler instead, which can non-zero exit the program.

Before:

    -$ ./m2ee.py start
    WARNING: Mendix Runtime not found for version 3.0.0. You can try downloading it using the download_runtime command.
    INFO: The application process is not running.
    INFO: Application Name: M2EE Test
    ERROR: It appears that the Mendix Runtime version which has to be used for your application is not present yet.
    INFO: You can try downloading it using the download_runtime command.
    -$ echo $?
    0

After:

   -$ ./m2ee.py start
    WARNING: Mendix Runtime not found for version 3.0.0. You can try downloading it using the download_runtime command.
    INFO: The application process is not running.
    INFO: Application Name: M2EE Test
    ERROR: It appears that the Mendix Runtime version which has to be used for your application is not present yet. You can try downloading it using the download_runtime command., errno: 0x1
    -$ echo $?
    1

Also see #5